### PR TITLE
Allow logo to redirect to root

### PR DESCRIPTION
**Pull request by ghost**
Makes the logo redirect to root when clicked, and that's about it.

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

If possible can you help with this issue here, when you click on the image and refresh the page we get a 404 error, can you fix it?

image

**Comment by ghost** [comment]
Seems to be an issue due to the fact that github pages assumes that those links are actual .html files, i'll take a look at this on another branch

**Comment by kbdharun** [comment]
> Seems to be an issue due to the fact that github pages assumes that those links are actual .html files, i'll take a look at this on another branch

Thanks

**Comment by mirkobrombin** [comment]
A workaround is adding a custom 404 page which actually forward to the vue router

**Comment by ghost** [comment]
> A workaround is adding a custom 404 page which actually forward to the vue router

Yup, was thinking the same thing

**Pull request merged**
